# Generated by Django 4.2.29 on 2026-05-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contactmessage_replied_at_contactmessage_replied_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='need_invoice',
            field=models.BooleanField(default=False, help_text='Customer requested an invoice'),
        ),
    ]
