# Generated by Django 4.2.29 on 2026-05-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours', models.CharField(default='Mon-Sat 08:00-20:00', help_text='Human readable work hours', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='+370 600 00000', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='contact@kasarium.local', max_length=254)),
                ('shipment_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Default shipment/courier price', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apartment / unit'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District / area'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='House number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_region',
            field=models.CharField(blank=True, max_length=100, verbose_name='State / region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street address'),
        ),
    ]
