# Generated by Django 4.2.29 on 2026-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings_customuser_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, default='Main Street 10, Vilnius, Lithuania', max_length=255),
        ),
    ]
