# Generated by Django 4.2.29 on 2026-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_data',
            field=models.TextField(blank=True),
        ),
    ]
