# Generated by Django 4.2.29 on 2026-05-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_kind',
            field=models.CharField(choices=[('percent', 'Percentage'), ('price', 'Discounted price')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
